# visualize_provenance_example.R
# This script demonstrates how to parse provenance JSON and create an elegant, 
# interactive network visualization in R.

# 1. Install necessary packages if missing
if (!require("jsonlite", quietly = TRUE)) install.packages("jsonlite", repos="http://cran.us.r-project.org")
if (!require("visNetwork", quietly = TRUE)) install.packages("visNetwork", repos="http://cran.us.r-project.org")
if (!require("rdtLite", quietly = TRUE)) install.packages("rdtLite", repos="http://cran.us.r-project.org")

library(jsonlite)
library(visNetwork)
library(rdtLite)

# 2. Generate provenance for our proposal workflow
message("Generating provenance for proposal_workflow.R...")
prov_json_str <- rdtLite::prov.run("proposal_workflow.R")
prov_data <- fromJSON(prov_json_str)

# 3. Extract nodes from PROV data
message("Parsing PROV-JSON data into a network...")
activities <- prov_data$activity
entities <- prov_data$entity

# Create Activity nodes (code executions, functions)
act_labels <- sapply(activities, function(x) {
  lbl <- x[["rdt:name"]]
  if (is.null(lbl)) return("Activity")
  # Truncate very long expressions for cleaner visualization
  if (nchar(lbl) > 35) lbl <- paste0(substr(lbl, 1, 32), "...")
  return(lbl)
})

act_nodes <- data.frame(
  id = names(activities),
  label = act_labels,
  group = "Activity",
  shape = "box",
  color.background = "#2B3A42",  # Elegant dark slate
  color.border = "#3F5765",
  color.highlight.background = "#3F5765",
  font.color = "#FFFFFF",
  font.face = "monospace",
  title = act_labels, # tooltip
  stringsAsFactors = FALSE
)

# Create Entity nodes (variables, datasets, files)
ent_labels <- sapply(entities, function(x) {
  lbl <- x[["rdt:name"]]
  if (is.null(lbl)) return("Entity")
  return(lbl)
})

ent_nodes <- data.frame(
  id = names(entities),
  label = ent_labels,
  group = "Entity",
  shape = "dot",
  size = 22,
  color.background = "#EFEFEF", # Clean light grey
  color.border = "#BDC3C7",
  color.highlight.background = "#FFFFFF",
  font.color = "#2C3E50",
  font.face = "Arial",
  title = ent_labels, # tooltip
  stringsAsFactors = FALSE
)

nodes <- rbind(act_nodes, ent_nodes)

# 4. Extract edges (relationships)
edges <- data.frame()

# Extract 'used' edges (Activity used Entity -> Entity to Activity)
if (!is.null(prov_data$used)) {
  used_edges <- data.frame(
    from = sapply(prov_data$used, function(x) x[["prov:entity"]]),
    to = sapply(prov_data$used, function(x) x[["prov:activity"]]),
    arrows = "to",
    color = "#95A5A6",
    label = "used",
    font.size = 10,
    font.color = "#7F8C8D",
    stringsAsFactors = FALSE
  )
  edges <- rbind(edges, used_edges)
}

# Extract 'wasGeneratedBy' edges (Entity was generated by Activity -> Activity to Entity)
if (!is.null(prov_data$wasGeneratedBy)) {
  gen_edges <- data.frame(
    from = sapply(prov_data$wasGeneratedBy, function(x) x[["prov:activity"]]),
    to = sapply(prov_data$wasGeneratedBy, function(x) x[["prov:entity"]]),
    arrows = "to",
    color = "#E74C3C", # Soft red for generation
    label = "generated",
    font.size = 10,
    font.color = "#C0392B",
    stringsAsFactors = FALSE
  )
  edges <- rbind(edges, gen_edges)
}

# 5. Render the interactive visualization
message("Rendering network...")
visNetwork(nodes, edges, main = "Provenance: Proposal Workflow", width = "100%", height = "800px") %>%
  visNodes(shadow = TRUE) %>%
  visEdges(smooth = list(type = "cubicBezier", forceDirection = "vertical")) %>%
  visOptions(
    highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE),
    nodesIdSelection = TRUE,
    selectedBy = "group"
  ) %>%
  visPhysics(
    solver = "hierarchicalRepulsion",
    hierarchicalRepulsion = list(nodeDistance = 150)
  ) %>%
  visLayout(hierarchical = list(
    enabled = TRUE,
    direction = "LR", # Left-to-Right timeline flow
    sortMethod = "directed"
  ))
